import { TarotCardData } from '@/types';

const majorArcana: TarotCardData[] = [
  {
    id: 'fool',
    name: 'The Fool',
    nameZh: '愚者',
    arcana: 'major',
    number: 0,
    keywords: ['新的开始', '冒险', '天真', '自由', ' spontaneity'],
    symbol: '🃏',
    love: '一段新的恋情即将萌芽，保持开放的心态，勇敢地迈出第一步。不要过度分析，跟随内心的指引。',
    career: '新的职业机会正在靠近。可能是创业、跳槽或者全新的项目。相信你的直觉，即使前路未卜。',
    health: '身体充满活力，适合开始新的健身计划。注意不要因为过度乐观而忽视必要的检查。',
    overall: '愚者象征着生命旅程的起点。此刻的你站在悬崖边，前方是无限可能。放下恐惧，带着好奇心出发，宇宙会接住你。',
  },
  {
    id: 'magician',
    name: 'The Magician',
    nameZh: '魔术师',
    arcana: 'major',
    number: 1,
    keywords: ['创造力', '意志力', '技能', '专注', '显化'],
    symbol: '🪄',
    love: '你拥有吸引理想伴侣的所有条件。主动展现真实的自己，你的魅力正在巅峰。',
    career: '所有资源都已就位——技能、人脉、机会。这是展示才华的最佳时机。将想法付诸行动。',
    health: '身心处于良好的平衡状态。任何健康目标只要开始就能看到成果。',
    overall: '魔术师提醒你：你拥有一切所需。天地间的能量正通过你流动。集中注意力，将梦想显化为现实。',
  },
  {
    id: 'high-priestess',
    name: 'The High Priestess',
    nameZh: '女祭司',
    arcana: 'major',
    number: 2,
    keywords: ['直觉', '潜意识', '神秘', '内在智慧', ' silence'],
    symbol: '🌙',
    love: '有些真相尚未浮出水面。相信你的直觉，静待时机。内在的声音比外界的意见更可靠。',
    career: '表面之下有重要的信息在流动。多听少说，观察同事的动机。正确的决定来自于深度的思考。',
    health: '关注心理健康。冥想、瑜伽或独处能帮助你恢复能量。身体的不适可能是情绪的信号。',
    overall: '女祭司是潜意识的守护者。答案不在外界，而在你的内心深处。安静下来，倾听内在的声音。',
  },
  {
    id: 'empress',
    name: 'The Empress',
    nameZh: '女皇',
    arcana: 'major',
    number: 3,
    keywords: ['丰饶', '滋养', '创造力', '自然', '母性'],
    symbol: '👑',
    love: '感情生活丰盛而美好。已有伴侣者关系更加亲密，单身者散发出不可抗拒的魅力。',
    career: '创意项目将获得丰收。这是一个适合"播种"和"培育"的时期，而非急于收割。',
    health: '身体状态良好，适合享受美食与自然的滋养。关注身体的需要，给自己充分的休息。',
    overall: '女皇代表着生命的丰饶。现在是拥抱感官享受、创造美好事物的时刻。让自己被美和舒适环绕。',
  },
  {
    id: 'emperor',
    name: 'The Emperor',
    nameZh: '皇帝',
    arcana: 'major',
    number: 4,
    keywords: ['权威', '秩序', '结构', '领导力', '稳定'],
    symbol: '🏰',
    love: '在爱情中需要建立清晰的边界。稳定和承诺比激情更重要。用责任和忠诚构建长久的关系。',
    career: '这是建立制度和流程的最佳时机。承担领导角色，你的决断力和组织能力将得到认可。',
    health: '建立规律的作息和锻炼习惯。自律是健康的基础。注意骨骼和关节。',
    overall: '皇帝代表着秩序与权威。用理性和纪律来构建你想要的生活。成为自己世界的主宰者。',
  },
  {
    id: 'lovers',
    name: 'The Lovers',
    nameZh: '恋人',
    arcana: 'major',
    number: 6,
    keywords: ['爱情', '和谐', '选择', '价值观', '结合'],
    symbol: '💕',
    love: '一段深刻的情感连接正在形成。这是关于灵魂层面的吸引。已有伴侣者面临关系升级的抉择。',
    career: '面临重要的职业选择。这个选择反映了你的核心价值观。选择你真正热爱的，而非仅看表面利益。',
    health: '身心和谐统一的时期。任何关于健康的选择都应基于对自己真实需求的理解。',
    overall: '恋人牌不仅仅是关于爱情，更是关于选择。你正在十字路口，每一个决定都将塑造你的未来。遵从内心。',
  },
  {
    id: 'chariot',
    name: 'The Chariot',
    nameZh: '战车',
    arcana: 'major',
    number: 7,
    keywords: ['胜利', '意志力', '决心', '控制', '前进'],
    symbol: '⚔️',
    love: '克服感情中的障碍。如果你在追求某人，现在是加大马力的时候。但记得保持平衡。',
    career: '竞争激烈的环境中你会胜出。坚定信念，保持专注。突破瓶颈的时刻到了。',
    health: '强大的意志力有助于克服健康挑战。注意不要过度消耗体力，保持身心的平衡。',
    overall: '战车代表着通过意志力实现的胜利。你已经装备齐全，只需要驾驭好内心的对立力量，勇往直前。',
  },
  {
    id: 'strength',
    name: 'Strength',
    nameZh: '力量',
    arcana: 'major',
    number: 8,
    keywords: ['勇气', '内在力量', '耐心', ' compassion', '驯服'],
    symbol: '🦁',
    love: '用温柔而非控制来经营感情。真正的力量是理解和包容。耐心将带来深厚的连接。',
    career: '面对挑战时展现内在的韧性。不需要大声宣告你的能力，让成果自己说话。',
    health: '身心都处于强大的恢复期。内在的力量正在帮助你克服任何健康问题。',
    overall: '力量牌教导我们：真正的力量不是征服，而是以柔克刚。你已经足够强大去面对一切。',
  },
  {
    id: 'hermit',
    name: 'The Hermit',
    nameZh: '隐者',
    arcana: 'major',
    number: 9,
    keywords: ['内省', ' solitude', '智慧', '指引', '探索'],
    symbol: '🏮',
    love: '暂时从感情世界抽离，审视自己真正的需求。独处不是逃避，而是为了更好地理解自己。',
    career: '寻求更深层次的目标和方向。可能适合独立工作或深入研究某个领域。向内寻找答案。',
    health: '关注精神健康。适当的独处和沉思有助于恢复内在平衡。注意睡眠质量。',
    overall: '隐者提着灯，在黑暗中寻找真理。此刻的你需要的不是外界的喧嚣，而是内心的宁静与智慧。',
  },
  {
    id: 'wheel-of-fortune',
    name: 'Wheel of Fortune',
    nameZh: '命运之轮',
    arcana: 'major',
    number: 10,
    keywords: ['命运', '转折', '周期', '幸运', '改变'],
    symbol: '🎡',
    love: '命运的红线正在牵引。一段命中注定的相遇或是关系的重大转折即将到来。',
    career: '运势正在上升。意想不到的机会可能随时出现。保持灵活，顺势而为。',
    health: '身体的周期和节奏正在调整。相信身体的自我修复能力。变化是积极的。',
    overall: '命运之轮提醒我们：一切都在循环中。好运将至，做好准备迎接生命的新阶段。',
  },
  {
    id: 'justice',
    name: 'Justice',
    nameZh: '正义',
    arcana: 'major',
    number: 11,
    keywords: ['公平', '真理', '因果', '责任', '决策'],
    symbol: '⚖️',
    love: '关系中的付出与回报将被平衡。诚实和公正是建立健康关系的基础。做出公正的判断。',
    career: '法律事务或合同将得到公正的处理。你的努力将获得应有的回报。做出正确的决定。',
    health: '平衡的生活方式是关键。任何极端的做法都会带来后果。寻求身心的平衡点。',
    overall: '正义提醒我们因果法则的存在。每一个选择都有其结果。以诚实和公正面对一切。',
  },
  {
    id: 'hanged-man',
    name: 'The Hanged Man',
    nameZh: '倒吊人',
    arcana: 'major',
    number: 12,
    keywords: ['牺牲', '悬置', '新视角', '放手', ' enlightenment'],
    symbol: '🔱',
    love: '可能需要做出牺牲或妥协。暂时放下自己的需求，从对方的角度看待问题。',
    career: '项目可能陷入停滞。这不是坏事——利用这段时间重新评估方向。换个角度思考。',
    health: '身体需要暂停和休息。不要强迫自己。有时候"不做什么"比"做什么"更重要。',
    overall: '倒吊人教导我们：有时候，放手才是获得。换个角度看世界，你会发现全新的可能性。',
  },
  {
    id: 'death',
    name: 'Death',
    nameZh: '死神',
    arcana: 'major',
    number: 13,
    keywords: ['结束', '转变', '重生', '放手', '蜕变'],
    symbol: '💀',
    love: '一段旧的关系模式正在终结。这不是结束，而是为新的开始腾出空间。放下过去。',
    career: '职业生涯的重大转变即将到来。可能是离职、转行或项目结束。拥抱变化。',
    health: '旧的不健康习惯需要彻底告别。身体正在经历深层的清理和更新。',
    overall: '死神牌并不代表真正的死亡，而是深刻的转变。旧的不去新的不来。迎接蜕变。',
  },
  {
    id: 'temperance',
    name: 'Temperance',
    nameZh: '节制',
    arcana: 'major',
    number: 14,
    keywords: ['平衡', ' moderation', '和谐', '融合', '耐心'],
    symbol: '🏺',
    love: '关系需要平衡和适度。不要太急也不要太慢。融合不同的需求找到共同的节奏。',
    career: '在工作中寻找平衡。团队合作比单打独斗更有效。避免极端的工作方式。',
    health: '一切适度。饮食、运动、休息都需要平衡。身体正在恢复和谐状态。',
    overall: '节制是融合与平衡的艺术。通过耐心和适度的调整，你正在创造内在的和谐。',
  },
  {
    id: 'devil',
    name: 'The Devil',
    nameZh: '恶魔',
    arcana: 'major',
    number: 15,
    keywords: ['束缚', '欲望', '物质主义', '阴影', ' liberation'],
    symbol: '😈',
    love: '检视关系中是否存在不健康的依赖或控制。有些"爱"可能只是执念。',
    career: '你是否被金钱或地位所困？真正的职业满足来自意义而非物质。',
    health: '注意上瘾行为。无论是食物、酒精还是其他，诚实地面对自己。',
    overall: '恶魔照出我们的阴影。那些束缚你的锁链，其实是你自己打造的。认识到这一点，你就自由了。',
  },
  {
    id: 'tower',
    name: 'The Tower',
    nameZh: '塔',
    arcana: 'major',
    number: 16,
    keywords: ['崩塌', '觉醒', ' revelation', '突破', '震撼'],
    symbol: '🗼',
    love: '一段建立在虚幻基础上的关系可能会崩塌。虽然痛苦，但这是为了让你看到真相。',
    career: '突如其来的变化可能打破安稳。这可能是被裁员或项目失败，但也打开了新的可能性。',
    health: '身体可能会发出强烈的信号提醒你注意。不要忽视任何突发的症状。',
    overall: '高塔的崩塌虽然令人恐惧，但它推倒的是虚假的结构。在废墟之上，才能建立真实的王国。',
  },
  {
    id: 'star',
    name: 'The Star',
    nameZh: '星星',
    arcana: 'major',
    number: 17,
    keywords: ['希望', ' healing', ' inspiration', '信心', ' renewal'],
    symbol: '⭐',
    love: '疗愈过去的感情创伤。新的希望在升起。相信你值得被爱，宇宙正在回应你的信念。',
    career: '灵感迸发的时期。追随你的热情所在。新的方向正在照亮你的道路。',
    health: '处于身心疗愈和恢复的阶段。积极的心态会加速康复。相信身体的自愈能力。',
    overall: '星星是黑暗后的第一缕光。经历了暴风雨，现在是疗愈和重建的时刻。保持希望与信心。',
  },
  {
    id: 'moon',
    name: 'The Moon',
    nameZh: '月亮',
    arcana: 'major',
    number: 18,
    keywords: ['直觉', ' illusion', '潜意识', '恐惧', '梦境'],
    symbol: '🌕',
    love: '关系中存在不明确的因素。不要被表面迷惑。相信直觉，但不要被恐惧驱使。',
    career: '信息不完整或存在误导。不要在这个阶段做重大决定。等待迷雾散去。',
    health: '关注睡眠质量和心理健康。梦境可能传递重要信息。焦虑可能是想象而非现实。',
    overall: '月光下的道路并不清晰。你的恐惧和想象可能会扭曲现实。保持冷静，等待黎明。',
  },
  {
    id: 'sun',
    name: 'The Sun',
    nameZh: '太阳',
    arcana: 'major',
    number: 19,
    keywords: ['喜悦', '成功', ' vitality', ' clarity', ' achievement'],
    symbol: '☀️',
    love: '感情生活充满阳光和温暖。这是最美好的一段时光。享受当下，分享你的快乐。',
    career: '才华被充分看见和认可。升职、成功、突破都在眼前。这是属于你的高光时刻。',
    health: '身体充满活力和能量。这是状态最好的时期。保持积极向上的生活方式。',
    overall: '太阳是塔罗牌中最积极的一张牌。一切都在闪耀。拥抱这份灿烂，你值得拥有这一切。',
  },
  {
    id: 'judgement',
    name: 'Judgement',
    nameZh: '审判',
    arcana: 'major',
    number: 20,
    keywords: ['觉醒', ' renewal', '召唤', '清算', '重生'],
    symbol: '📯',
    love: '过往的感情经历需要被审视和释放。宽恕自己和他人。新的开始需要干净的内心。',
    career: '你的努力正在被评估。可能会收到重要的反馈或结果。这是一个阶段的总结。',
    health: '身体在进行深层的自我修复。倾听身体的声音，做出必要的调整。',
    overall: '审判的号角已吹响。这是觉醒和重生的时刻。回应内心深处的召唤，拥抱全新的自己。',
  },
  {
    id: 'world',
    name: 'The World',
    nameZh: '世界',
    arcana: 'major',
    number: 21,
    keywords: ['完成', '成就', '圆满', '旅程', '整合'],
    symbol: '🌍',
    love: '感情关系达到一个新的圆满阶段。可能是婚姻、承诺或灵魂层面的完整融合。',
    career: '一个重要的职业周期即将圆满结束。你已经掌握了所需的一切。庆祝你的成就。',
    health: '身心达到整体平衡的最佳状态。整合所有的经验和教训，迈向更健康的生活。',
    overall: '世界牌代表一个完整周期的结束。你已经完成了重要的旅程。庆祝吧，你已到达。',
  },
];

// 12 cards for the default spread
export const defaultSpreadCards: TarotCardData[] = [
  majorArcana[0],   // The Fool
  majorArcana[1],   // The Magician
  majorArcana[2],   // The High Priestess
  majorArcana[3],   // The Empress
  majorArcana[4],   // The Emperor
  majorArcana[5],   // The Lovers
  majorArcana[6],   // The Chariot
  majorArcana[7],   // Strength
  majorArcana[8],   // The Hermit
  majorArcana[9],   // Wheel of Fortune
  majorArcana[10],  // Justice
  majorArcana[17],  // The Star
];

export const allCards: TarotCardData[] = majorArcana;

export function getRandomCards(count: number): TarotCardData[] {
  const shuffled = [...majorArcana].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export function getCardById(id: string): TarotCardData | undefined {
  return majorArcana.find((c) => c.id === id);
}
